#!/usr/bin/python
import subprocess

print "mono build/FpgaTest.exe --run \"FsCheck/Data that is written can be read later\""
args = ["unbuffer", "mono","build/FpgaTest.exe", "--run",  "FsCheck/Data that is written can be read later"]
subprocess.call(args)
