#!/usr/bin/python
import subprocess

print "mono build/FpgaTest.exe --run \"FsCheck/Data that is written can be read later - Stress\""
args = ["mono","build/FpgaTest.exe", "--run",  "FsCheck/Data that is written can be read later - Stress"]
subprocess.call(args)
